USE [master]
GO

/****** Object:  Database [BDPoC]    Script Date: 03/08/2020 19:01:52 ******/
CREATE DATABASE [BDPoC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BDPoC', FILENAME = N'C:\Users\ferci\BDPoC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BDPoC_log', FILENAME = N'C:\Users\ferci\BDPoC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [BDPoC] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDPoC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BDPoC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BDPoC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BDPoC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BDPoC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BDPoC] SET ARITHABORT OFF 
GO

ALTER DATABASE [BDPoC] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BDPoC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BDPoC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BDPoC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BDPoC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BDPoC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BDPoC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BDPoC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BDPoC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BDPoC] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BDPoC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BDPoC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BDPoC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BDPoC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BDPoC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BDPoC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BDPoC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BDPoC] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BDPoC] SET  MULTI_USER 
GO

ALTER DATABASE [BDPoC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BDPoC] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BDPoC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BDPoC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BDPoC] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BDPoC] SET QUERY_STORE = OFF
GO

USE [BDPoC]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [BDPoC] SET  READ_WRITE 
GO


USE [BDPoC]
GO

/****** Object:  Table [dbo].[CLIENTE]    Script Date: 03/08/2020 19:11:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENTE](
	[ID_CLIENTE] [int] IDENTITY(1,1) NOT NULL,
	[NM_CLIENTE] [nvarchar](150) NOT NULL,
 CONSTRAINT [PK__CLIENTE] PRIMARY KEY CLUSTERED 
(
	[ID_CLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ__CLIENTE_NOME] UNIQUE NONCLUSTERED 
(
	[NM_CLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [BDPoC]
GO

/****** Object:  Table [dbo].[PRODUTO]    Script Date: 03/08/2020 19:12:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUTO](
	[ID_PRODUTO] [int] IDENTITY(1,1) NOT NULL,
	[NM_PRODUTO] [nvarchar](150) NOT NULL,
 CONSTRAINT [PK__PRODUTO] PRIMARY KEY CLUSTERED 
(
	[ID_PRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ__PRODUTO_NOME] UNIQUE NONCLUSTERED 
(
	[NM_PRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [BDPoC]
GO

/****** Object:  Table [dbo].[COMPRA]    Script Date: 03/08/2020 19:12:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMPRA](
	[ID_COMPRA] [int] IDENTITY(1,1) NOT NULL,
	[ID_CLIENTE] [int] NOT NULL,
	[ID_PRODUTO] [int] NOT NULL,
 CONSTRAINT [PK__COMPRA] PRIMARY KEY CLUSTERED 
(
	[ID_COMPRA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[COMPRA]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_CLIENTE] FOREIGN KEY([ID_CLIENTE])
REFERENCES [dbo].[CLIENTE] ([ID_CLIENTE])
GO

ALTER TABLE [dbo].[COMPRA] CHECK CONSTRAINT [FK_COMPRA_CLIENTE]
GO

ALTER TABLE [dbo].[COMPRA]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_PRODUTO] FOREIGN KEY([ID_PRODUTO])
REFERENCES [dbo].[PRODUTO] ([ID_PRODUTO])
GO

ALTER TABLE [dbo].[COMPRA] CHECK CONSTRAINT [FK_COMPRA_PRODUTO]
GO



